server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:4200"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
            allowed-headers:
              - "*"
